import {
  Box,
  Button,
  Card,
  CardImage,
  Center,
  Cluster,
  Image,
  Link,
  Sidebar,
  Spacer,
  Stack,
  Switch,
  Switcher,
  Text,
} from "@reframe.so/blocks";

export default function App() {
  return (
    <Stack
      data-reframe-id="root"
      direction={"column"}
      recursive={false}
      splitAfter={"-1"}
      alignItems={"stretch"}
      space={1}
      padding={0}
    >
      <Box
        data-reframe-id="b53f7bd6-add3-4c90-aee7-24ec2cb9191e"
        padding={"$1"}
        borderWeight={0}
        borderRadius={0}
        shadow={0}
        grow={false}
      >
        <Box
          data-reframe-id="edc4e014-e6a7-4f7c-aeb7-02418f713dd1"
          padding={"$1"}
          borderWeight={0}
          borderRadius={0}
          shadow={0}
          grow={false}
        >
          <Card
            data-reframe-id="cd5d3d4b-0e96-41c4-ad1c-f01de30d9577"
            animated={true}
            ripple={true}
            cover={false}
            preventDefault={false}
            shadow={true}
            bordered={false}
            hoverable={false}
            clickable={false}
            borderWeight={"normal"}
            color={"red"}
          >
            DEF
          </Card>
        </Box>

        <Text
          data-reframe-id="d25bd998-30fd-456c-9ef0-06963a5a3c9d"
          h1={false}
          h2={false}
          h3={false}
          h4={false}
          h5={false}
          h6={false}
          b={false}
          small={false}
          transform={"none"}
          i={false}
          span={false}
          del={false}
          em={false}
          blockquote={false}
          color={"default"}
        >
          Abc
        </Text>
      </Box>
    </Stack>
  );
}
